version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"  # Changed port mapping to 8085
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - mynet

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfonyuser
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3306:3306"
    networks:
      - mynet

networks:
  mynet:
